# Generated by Django 2.2.7 on 2020-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsforsale',
            name='set_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='available_cards',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
