# Generated by Django 2.1.7 on 2020-07-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0005_auto_20200727_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_cards',
        ),
    ]
