# Generated by Django 2.1.7 on 2020-07-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0008_remove_card_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_name',
            new_name='name',
        ),
    ]
