# Generated by Django 2.1.7 on 2020-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0009_auto_20200727_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_foil',
            field=models.BooleanField(default=False),
        ),
    ]
