# Generated by Django 2.1.7 on 2020-08-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0010_card_is_foil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.FileField(default='settings.MEDIA_ROOT/Magic_card_back.jpg', upload_to=''),
        ),
    ]
