# Generated by Django 2.1.7 on 2020-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0016_auto_20200810_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='imageUrl',
            field=models.TextField(default=[]),
        ),
    ]
