# Generated by Django 2.2.7 on 2020-08-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0017_card_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='imageUrl',
        ),
    ]
