# Generated by Django 2.2.7 on 2020-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0019_auto_20200814_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_photo', models.FileField(default='profile_images/Magic_card_back.jpg', upload_to='profile_images')),
            ],
        ),
    ]
