# Generated by Django 2.2.7 on 2020-08-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0020_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
