# Generated by Django 2.2.7 on 2020-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0021_delete_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='card_photos/Magic_card_back.jpg', upload_to='card_photos')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.FloatField(),
        ),
    ]
