# Generated by Django 2.1.7 on 2020-08-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0022_auto_20200815_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.FileField(default='profile_images/default-profile-picture.jpg', upload_to='profile_images'),
        ),
    ]
