# Generated by Django 2.1.7 on 2020-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0023_auto_20200820_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
