# Generated by Django 2.2.7 on 2020-09-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0026_remove_card_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
