# Generated by Django 3.1.1 on 2020-10-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0031_auto_20200921_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='imageUrl',
            field=models.TextField(default='http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=426721&type=card'),
        ),
    ]
