# Generated by Django 3.1.1 on 2020-10-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0032_card_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='imageUrl',
        ),
    ]
