# Generated by Django 3.1.1 on 2020-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0033_remove_card_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='imageUrl',
            field=models.TextField(default=False),
        ),
    ]
