# Generated by Django 3.1.1 on 2020-10-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0034_card_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
