# Generated by Django 3.1.1 on 2020-10-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0035_auto_20201018_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_url',
            field=models.TextField(blank=True, default=False),
        ),
    ]
