# Generated by Django 3.1.1 on 2020-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0040_auto_20201018_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.IntegerField(),
        ),
    ]
